### ISSUE TITLE
bots decision making improvement

### ISSUE THREAD

**Issue by kotc** [jdmonin/JSettlers2#27]
hello,

while i enjoy this game (and play beta exclusively, i must say bots ai is not optimized. situation: i have 2VP, other human player has 4VP, both bots also have more than 2VP, yet, they place robber againt me. multiple times in consecutive rolls. what makes them hate particular player? or it's just random roll whom to punish? and it's not the only time, i've seen that in multiple games.

**Comment by jdmonin** [comment]
Hello,

That's a good question. There's more than one bot strategy routine. Often instead of moving against the player with the most VP, a bot will target the player who can be slowed down the most by a particular move. This sometimes means moves that aren't optimal.

Thanks for enjoying the game and using the beta!

**Comment by kotc** [comment]
what i've noticed is that hving a port with the same resource makes it high priority target. i had 2 pts, gf had 9, yet i've been targetted 3 times in a row. imo leading player (or the one endangering particular bot, ie. to block neighboring player from builing up)
