### ISSUE TITLE
Use newer graphics?

### ISSUE THREAD

**Issue by qubodup** [jdmonin/JSettlers2#64]
Hi,

I made this theme for jsettlers2 years ago: https://opengameart.org/content/pastel-resources-hex-tiles-55x64-and-64x55

It is compatibly licensed. If you like it, I'd love to see it be the official imageset.

I can try to assist with replacing the gold tile with a similar style as well as the portraits, which seem to be random downloaded icons.

Cheers!

**Comment by jdmonin** [comment]
Hi,

Thank you for your generous offer! I did a quick test run, and the results are promising; details below.

A few overall comments first:
- I like how they look, good style.
- If you'd like, you're welcome to make a gold tile with the same style. The current gold tile looks alright with your set, so if you'd rather not make one, that's OK too.
- I think I'll also provide the current "classic" tiles, and give users an option in the interface for which set they want to use
- The icons/portraits would be a lot or work, so that's up to you. I saw your post analyzing the art contents of various Settlers implementations, thanks for that. If a few portraits are causing trouble from a "clean assets" point of view, maybe those few are the place to start.

So, the test run: Overall, things look very nice!  The way the hexes are packaged and generated has changed a bit since your set was made, so my thoughts are:
- Could you please remove borders from the hexes? At this point the image should go all the way to the edge of the hex, and the borders are drawn as vector lines at final resolution
- You won't need port or miscPort hexes; those are generated from the others
- The ore hex is lighter than the others, and the white player's pieces get a little lost around it. What would you think of making it a bit grayer and maybe reducing its contrast (fewer dark shadows)?
- I'll need to adjust the "current player" arrow color, it's very close to the pastel water hexes

Let me know what you think. Thanks again!
-Jeremy

4-player board:
![4-player board](http://nand.net/jsettlers/misc/pastel_4pl_20190730.png)

6-player board:
![6-player board](http://nand.net/jsettlers/misc/pastel_6pl_20190730.png)

Sea board: Forgotten Tribe scenario
![Sea board: Forgotten Tribe scenario](http://nand.net/jsettlers/misc/pastel_sea_ftri_20190730.png)

**Comment by jdmonin** [comment]
Since the new JSettlers version uses more water on-screen than the old version, the water's color has more of an effect on the overall look. What do you think of something like this slight tone change?

![4-player board](http://nand.net/jsettlers/misc/pastel_4pl_20190801.png)

![Sea board: Forgotten Tribe scenario](http://nand.net/jsettlers/misc/pastel_sea_ftri_20190801.png)

In GIMP this was done with Adjust color balance: cyan->red 13, yellow->blue 9;  Then brightness +28 contrast +10

**Comment by qubodup** [comment]
Glad you approve! Thanks for the screenshots!

I started a repository for the tiles:  https://github.com/qubodup/pastel-tiles

Can I test the endless water tiles or the forgotten tribe scenario and/or gold tiles somehow?

Is it possible to increase the tile size, for example to 77x66 /66x77? They work perfectly well if I replace most gif files with bigger images, but once I replace desertHex.gif, all of them scale weirdly:
![image](https://user-images.githubusercontent.com/18312/62413449-75e1ae80-b60f-11e9-9419-bcbc1f81e863.png)

If not, I can simply keep the desert tile at 55x64 while the other tiles can enjoy a higher resolution.

The changed water looks slightly violet to me but I haven't playtested yet. Did you change it to make the arrow more visible? (Maybe making the current player arrow white would help.) Or was it an attempt to tackle something else?

I reduced the contrast of the mountains, made a gold tile, removed borders:
![image](https://user-images.githubusercontent.com/18312/62413964-2a7ece80-b616-11e9-9975-8a4da297e0a3.png)

**Comment by jdmonin** [comment]
I'm still looking into your questions; I don't want to leave you hanging, so here are a few things :)

- That mountain tile looks good, thanks! Your screenshot looks cleaner without the borders, thanks for taking care of those too.

- You can test scenarios, gold, and endless water by replacing GIFs in the 2.0 beta JAR, which you can download from http://nand.net/jsettlers/beta2/

- We should be able to increase tile size once I update some code: Right now `SOCBoardPanel` has assumptions about the tile GIF dimensions. In `rescaleBoard()` it uses 1 tile to get the dimensions of all of them, and I think in version 1.x that tile was desertHex. In 2.0 it's waterHex.

- A neutral arrow color is a good suggestion; maybe light gray or white

- Because there's so much water on screen, personally I prefer it a little less cyan and more blue. Probably my first attempt went too far towards purple.  Here's another try, let me know what you think. This is with Color balance: yellow->blue 9; then Brightness +10 contrast +5.

![4-player board](http://nand.net/jsettlers/misc/pastel_4pl_20190805.png)

![Sea board: Forgotten Tribe scenario](http://nand.net/jsettlers/misc/pastel_sea_ftri_20190805.png)

**Comment by jdmonin** [comment]
OK, I've uploaded a new client jar to http://nand.net/jsettlers/beta2/ which uses light gray for the player arrow.

**Comment by qubodup** [comment]
Thanks, I like the "**Color balance: yellow->blue 9; then Brightness +10 contrast +5**" one better.

If you think it'd benefit visuals and you're up for implementing it, different graphics for shore and non-shore water could be done. Mockup (not actual suggestion what it should look like):
![test](https://user-images.githubusercontent.com/18312/62541595-5e4a3600-b85a-11e9-8229-6d80f1246725.jpg) (whoops, missed a tile at the bottom left)

**Comment by jdmonin** [comment]
OK thanks, I think we both agree on that color then :) Would you mind updating the water in your repo?

Shore and non-shore is an interesting suggestion. Maybe in a future version?

**Comment by jdmonin** [comment]
OK, the latest beta JAR at http://nand.net/jsettlers/beta2/ can now deal with the 77x66/66x77 tile sizes.

If my PR at qubodup/pastel-tiles looks good to you, once merged I can update the code to offer both tile sets.

**Comment by qubodup** [comment]
Sorry for the wait and thanks for the effort providing new jars. I tried making the change using imagemagick only. All hex tiles are now generated in the script using masks rather than rotation. If you don't like the water, you could play around with `-channel B -level 9% -channel All -brightness-contrast 0x10` or remove that part and use your modified xcfbz2 as a basis.

![image](https://user-images.githubusercontent.com/18312/63217515-b715aa80-c147-11e9-83fd-e668abff9ba8.png)

**Comment by jdmonin** [comment]
Very cool! Your imagemagick-adjusted water looks great. Thanks for doing that and scripting all the rotated ones.

**Comment by jdmonin** [comment]
OK, I'm making good progress integrating your graphics set. Very exciting :)

For attribution in Readme, what name would you like me to put? Right now I have "created and contributed by qubodup".  Thanks

**Comment by jdmonin** [comment]
OK, I'm making good progress integrating your graphics set. Very exciting :)

For attribution in Readme, what name would you like me to put? Right now I have "created and contributed by qubodup". I can keep that or use whatever else you'd prefer. Thanks

**Comment by qubodup** [comment]
Pardon, got swamped and found this cleaning up my inbox - Thanks, that attribution is great like this!

**Comment by jdmonin** [comment]
Okay cool. No worries :) Thanks for all the work you put into it!

**Comment by jdmonin** [comment]
Newly released v2.0.00 includes your graphics set as the default, and mine as a "classic" option. Thanks again! :)
